spring:
  profiles:
    active: dev
  rabbitmq:
    host: ${RABBIT_MQ_HOST:172.16.0.6}
    port: ${RABBIT_MQ_PORT:31713}
    username: ${RABBIT_MQ_USERNAME:user}
    password: ${RABBIT_MQ_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:172.16.0.8}
    port: ${REDIS_PORT:31268}
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:172.16.0.6}:${DATASOURCE_PORT:31372}/sc_gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:uXsR08Ijsd}

#  zipkin:
#    enabled: true
#    sender:
#      type: rabbit
#  sleuth:
#    enabled: true
#    http:
#      legacy:
#        enabled: true

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.springboot.cloud
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis.lettuce
      uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}/
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
#      valueEncoder: kryo
#      valueDecoder: kryo
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB